[project]
name = "starmap"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "flask>=3.1.2",
    "openpyxl>=3.1.5",
    "pandas>=3.0.0",
]
